[build]
  publish = "static"
  command = "echo 'Serving static; proxying to backend via function'"

[functions]
  node_bundler = "esbuild"

# Set BACKEND_URL in Netlify environment variables (e.g., Render or Vercel URL)
# Send all requests through the proxy function, preserving path
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/proxy/api/:splat"
  status = 200

[[redirects]]
  from = "/chat"
  to = "/.netlify/functions/proxy/chat"
  status = 200

[[redirects]]
  from = "/models"
  to = "/.netlify/functions/proxy/models"
  status = 200

[[redirects]]
  from = "/"
  to = "/.netlify/functions/proxy/"
  status = 200
